Repository Kernel180-BE12/final_6team_pls_jober, pull requests merged in 2025-09, with the labels that each got.

#3 Feature/front landing
  .github/pull_request_template.md
  front/src/components/ForgotPasswordComponent.vue
  front/src/components/HeaderComponent.vue
  front/src/components/LoginComponent.vue
  front/src/components/RegisterComponent.vue
  front/src/router/index.ts
  front/src/views/AboutView.vue
  front/src/views/HomeView.vue
  front/src/views/LandingView.vue
  front/tsconfig.app.json
Labels: enhancement

#10 Feature/back login
  .github/pull_request_template.md
  back/src/main/java/com/example/config/SecurityConfig.java
  back/src/main/java/com/example/controller/AuthController.java
  back/src/main/java/com/example/dto/LoginRequest.java
  back/src/main/java/com/example/dto/SignupRequest.java
  back/src/main/java/com/example/service/AuthService.java
  back/src/main/resources/application.yml
Labels: enhancement

#17 refactor: Account 엔티티 id 이름 일치하게 수정
  back/src/main/java/com/example/common/AuthSupport.java
  back/src/main/java/com/example/controller/UserController.java
  back/src/main/java/com/example/entity/Account.java
  back/src/main/java/com/example/repository/AccountRepository.java
  back/src/main/java/com/example/repository/UserRepository.java
  back/src/main/java/com/example/service/MyPageService.java
  back/src/main/java/com/example/service/UserService.java
Labels: refactoring

#15 Feature/chat
  .gitignore
  back/build.gradle
  back/src/main/java/com/example/BackApplication.java
  back/src/main/java/com/example/config/SecurityConfig.java
  back/src/main/java/com/example/controller/TemplateController.java
  back/src/main/java/com/example/dto/FastAPIRequestDto.java
  back/src/main/java/com/example/dto/FastAPIResponseDto.java
  back/src/main/java/com/example/dto/TemplateRequestDto.java
  back/src/main/java/com/example/dto/TemplateResponseDto.java
  back/src/main/java/com/example/entity/Account.java
  back/src/main/java/com/example/entity/Category1.java
  back/src/main/java/com/example/entity/Category2.java
  back/src/main/java/com/example/entity/Industry.java
  back/src/main/java/com/example/entity/PolicyRef.java
  back/src/main/java/com/example/entity/Template.java
  back/src/main/java/com/example/entity/Var.java
  back/src/main/java/com/example/exception/ResourceNotFoundException.java
  back/src/main/java/com/example/repository/AccountRepository.java
  back/src/main/java/com/example/repository/Category2Repository.java
  back/src/main/java/com/example/repository/IndustryRepository.java
  back/src/main/java/com/example/repository/TemplateRepository.java
  back/src/main/java/com/example/service/AIService.java
  back/src/main/java/com/example/service/TemplateService.java
  back/src/main/resources/application.yml
Labels: enhancement

#20 Feature/ai/template generation
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  README.md
  ai/README.md
  ai/main.py
  ai/multiple_test.py
  ai/requirements.txt
  ai/services/chromadb_service.py
  ai/templateEngine/__init__.py
  ai/templateEngine/template_generator.py
  ai/updated_test.py
Labels: enhancement

#16 Feature: Flyway 마이그레이션 초기 설정
  back/build.gradle
  back/src/main/resources/application.yml
  back/src/main/resources/db/migration/V0_init.sql
Labels: enhancement

#35 refactor: 필드 추출 프롬프트 강화 & 힌트 적용
  ai/templateEngine/message_analyzer/message_analyzer.py
  ai/templateEngine/message_analyzer/prompts/base_prompt_builder.py
  ai/templateEngine/message_analyzer/prompts/build_category_prompt.py
  ai/templateEngine/message_analyzer/prompts/build_fields_prompt.py
  ai/templateEngine/message_analyzer/prompts/build_type_prompt.py
Labels: enhancement, refactoring

#36 Feature/ai/base
  README.md
  ai/README.md
  ai/config/__init__.py
  ai/config/constraint_rules.yaml
  ai/data/__init__.py
  ai/data/alimtalk_guidelines.json
  ai/data/example_templates.json
  ai/main.py
  ai/models/alimtalk_models.py
  ai/multiple_test.py
  ai/requirements.txt
  ai/routers/alimtalk_routes.py
  ai/services/alimtalk_service.py
  ai/services/chromadb_service.py
  ai/templateEngine/__init__.py
  ai/templateEngine/extractor.py
  ai/templateEngine/generator.py
  ai/templateEngine/message_analyzer/__init__.py
  ai/templateEngine/message_analyzer/message_analyzer.py
  ai/templateEngine/message_analyzer/prompts/__init__.py
  ai/templateEngine/message_analyzer/prompts/base_prompt_builder.py
  ai/templateEngine/message_analyzer/prompts/build_category_prompt.py
  ai/templateEngine/message_analyzer/prompts/build_fields_prompt.py
  ai/templateEngine/message_analyzer/prompts/build_type_prompt.py
  ai/templateEngine/templateOrchestrator.py
  ai/templateEngine/template_generator.py
  ai/templateEngine/validator.py
  ai/tests/__init__.py
  ai/tests/unit/__init__.py
  ai/tests/unit/message_analyzer/__init__.py
  ai/tests/unit/message_analyzer/analyze_message_test.py
  ai/updated_test.py
  ai/validators/__init__.py
  ai/validators/constraint_validator.py
  ai/validators/final_validation_prompt.py
  ai/validators/schema_validator.py
  ai/validators/semantic_validator.py
  ai/validators/validator_pipeline.py
Labels: enhancement

#37 Refactor/connect all
  README.md
  ai/env.example
  ai/multiple_test.py
  ai/routers/ai_routes.py
  ai/templateEngine/extractor.py
  ai/templateEngine/generator.py
  ai/templateEngine/templateOrchestrator.py
  ai/templateEngine/validator.py
  ai/updated_test.py
  back/src/main/java/com/example/config/JwtTokenProvider.java
  back/src/main/java/com/example/config/SecurityConfig.java
  back/src/main/java/com/example/controller/AccountController.java
  back/src/main/java/com/example/controller/AuthController.java
  back/src/main/java/com/example/controller/TemplateController.java
  back/src/main/java/com/example/dto/TemplateValidationRequestDto.java
  back/src/main/java/com/example/dto/TemplateValidationResponseDto.java
  back/src/main/java/com/example/entity/Template.java
  back/src/main/java/com/example/repository/Category2Repository.java
  back/src/main/java/com/example/service/AIService.java
  back/src/main/java/com/example/service/AuthService.java
  back/src/main/java/com/example/service/TemplateService.java
  front/package-lock.json
  front/package.json
  front/src/api/index.ts
  front/src/components/KakaoPreviewComponent.vue
  front/src/components/LoginComponent.vue
  front/src/stores/counter.ts
  front/src/views/TemplateCreateView.vue
  front/src/views/TemplateResultView.vue
Labels: enhancement

#66 fix: CI.yml 수정
  .github/workflows/CI.yml
  ai/requirements.txt
Labels: bug

#67 refactor: 헤더 버튼 수정
  back/src/main/java/com/example/service/TokenService.java
  front/src/components/HeaderComponent.vue
  front/src/components/LoginComponent.vue
  front/src/stores/user.ts
  front/src/views/LandingView.vue
Labels: refactoring

#69 fix : #61 refactor: #68 openai 호출 오류 및 생성 시 카테고리 부분 삭제
  ai/services/openai_service.py
  ai/templateEngine/template_generator.py
  ai/validators/semantic_validator.py
  back/src/main/java/com/example/config/SecurityConfig.java
  back/src/main/java/com/example/dto/FastAPIRequestDto.java
  back/src/main/java/com/example/dto/FastAPIResponseDto.java
  back/src/main/java/com/example/service/AIService.java
  front/src/api/index.ts
  front/src/views/TemplateCreateView.vue
  front/src/views/TemplateResultView.vue
Labels: refactoring

#101 카카오 소셜 로그인 기능 개발
  .github/pull_request_template.md
  back/.env.example
  back/build.gradle
  back/src/main/java/com/example/config/JwtAuthenticationFilter.java
  back/src/main/java/com/example/config/JwtTokenProvider.java
  back/src/main/java/com/example/config/SecurityConfig.java
  back/src/main/java/com/example/config/WebClientConfig.java
  back/src/main/java/com/example/config/WebConfig.java
  back/src/main/java/com/example/controller/KakaoController.java
  back/src/main/java/com/example/dto/KakaoUserInfo.java
  back/src/main/java/com/example/service/KakaoService.java
  back/src/main/resources/application.yml
  back/src/main/resources/static/favicon.ico
  back/src/test/java/com/example/controller/KakaoControllerTest.java
  back/src/test/java/com/example/controller/KakaoControllerTestConfig.java
  back/src/test/resources/application-test.yml
  front/public/kakao-callback.html
  front/src/api/index.ts
  front/src/components/LoginComponent.vue
  front/src/components/RegisterComponent.vue
  front/src/views/LandingView.vue
Labels: enhancement

#97 refactor: AI API에서 인증 미들웨어 제거
  ai/routers/ai_routes.py
Labels: enhancement

#106 fix: 템플릿 수정 에러 해결 및 기능 개선
  ai/routers/ai_routes.py
  back/src/main/java/com/example/dto/TemplateRequestDto.java
  front/src/api/index.ts
  front/src/components/TemplateCreateComponent.vue
  front/src/views/TemplateResultView.vue
Labels: enhancement

#124 refactor: AI 템플릿 생성 로직 고도화
  ai/api/routes/template_routes.py
  ai/config/__init__.py
  ai/core/constants.py
  ai/exceptions.py
  ai/main.py
  ai/middleware/auth_middleware.py
  ai/routers/ai_routes.py
  ai/services/alimtalk_service.py
  ai/services/chromadb_service.py
  ai/services/dependencies.py
  ai/services/openai_service.py
  ai/templateEngine/__init__.py
  ai/templateEngine/integrated_template_pipeline.py
  ai/templateEngine/message_analyzer.py
  ai/templateEngine/nodes.py
  ai/templateEngine/pipeline.py
  ai/templateEngine/prompts/__init__.py
  ai/templateEngine/prompts/builders.py
  ai/templateEngine/prompts/final_validation_prompt.py
  ai/templateEngine/prompts/message_analyzer_prompts.py
  ai/templateEngine/state.py
  ai/templateEngine/template_generator.py
  ai/tests/unit/message_analyzer/__init__.py
  ai/tests/unit/message_analyzer/async_test.py
  ai/tests/unit/metadata_test.py
  ai/validators/final_validation_prompt.py
  ai/validators/semantic_validator.py
  ai/validators/validator_pipeline.py
  back/src/main/java/com/example/controller/TemplateController.java
  back/src/main/java/com/example/service/AIService.java
  back/src/main/java/com/example/service/TemplateService.java
  back/src/main/resources/application-local.yml
  back/src/main/resources/application.yml
  back/src/test/resources/application-test.yml
  front/package.json
  front/src/api/ai.ts
  front/src/api/index.ts
  front/src/components/KakaoPreviewComponent.vue
  front/src/components/RejectionSidebarComponent.vue
  front/src/views/TemplateResultView.vue
Labels: enhancement, refactoring
